"""Amalgamate TinyReflection's multi-file headers into a single header.

The multi-file sources under `tinyrefl/` are always the source of truth.
The single header generated here is a build artifact for users who want a
"drop one file in and go" experience; it must never be hand-edited.

Deduplication here is done per resolved file path (a `visited` set), not by
parsing each file's include-guard style. This project vendors third-party
headers (rapidjson, frozen) that use classic `#ifndef`/`#define` guards with
inconsistent naming (e.g. `RAPIDJSON_RAPIDJSON_H_` vs `RAPIDJSON_POW10_` vs
`FROZEN_LETITGO_STRING_H`), mixed alongside tinyrefl's own `#pragma once`
headers. A generic amalgamation tool that only recognizes one guard style
(or needs a hand-tuned regex per vendored library) either duplicates content
or risks misidentifying non-guard feature-flag macros as guards. Path-based
deduplication sidesteps that entirely: it doesn't need to understand any
guard convention.

Usage:
    python3 scripts/amalgamate.py              # regenerate single_include/tinyrefl.hpp
    python3 scripts/amalgamate.py --check       # verify it's up to date (CI-friendly, no write)
"""
import argparse
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
TINYREFL_DIR = PROJECT_ROOT / "tinyrefl"
THIRDPARTY_DIR = TINYREFL_DIR / "thirdparty"
DEFAULT_OUTPUT = PROJECT_ROOT / "single_include" / "tinyrefl.hpp"

# Mirrors the search path order configured in target_include_directories(tinyrefl
# INTERFACE ...) in CMakeLists.txt: first look relative to the including file,
# then fall back to these directories.
FALLBACK_SEARCH_DIRS = [PROJECT_ROOT, TINYREFL_DIR, THIRDPARTY_DIR]

# Entry headers; every other local file is pulled in transitively by expanding
# their #include "..." directives.
ENTRY_HEADERS = [
    TINYREFL_DIR / "reflection_to_json.hpp",
    TINYREFL_DIR / "reflection_from_json.hpp",
]

LOCAL_INCLUDE_RE = re.compile(r'^\s*#\s*include\s*"([^"]+)"')
PRAGMA_ONCE_RE = re.compile(r'^\s*#\s*pragma\s+once\s*$')

HEADER_BANNER = """\
// =====================================================================
// TinyReflection -- single-header amalgamation
//
// Auto-generated by scripts/amalgamate.py. DO NOT EDIT DIRECTLY.
// Any change must be made to the multi-file sources under tinyrefl/,
// then regenerate this file with:
//     python3 scripts/amalgamate.py
//
// This file is assembled from tinyrefl/ and tinyrefl/thirdparty/
// (rapidjson, frozen) following their #include dependency graph; each
// vendored library's copyright/license notice is preserved inline below.
// =====================================================================
"""


def scan_lines(text: str):
    """Yield (line, is_code) pairs.

    is_code=False marks a line that lies inside a multi-line block comment
    (/* ... */). Some vendored headers (e.g. rapidjson.h) embed Doxygen
    \\code examples containing lines that look like real #include
    directives (e.g. `#include "rapidjson/..."`); those must not be parsed
    as actual preprocessor directives, or real code would get spliced into
    a comment block.
    """
    in_block_comment = False
    for line in text.splitlines():
        if in_block_comment:
            if "*/" in line:
                in_block_comment = False
            yield line, False
            continue
        open_idx = line.find("/*")
        if open_idx != -1 and "*/" not in line[open_idx + 2:]:
            in_block_comment = True
            yield line, False
            continue
        yield line, True


def resolve_local_include(current_dir: Path, include_path: str):
    """Resolve a quoted #include the way a compiler would: check the
    including file's own directory first, then fall back to
    FALLBACK_SEARCH_DIRS (matching the CMakeLists.txt search paths)."""
    candidate = (current_dir / include_path).resolve()
    if candidate.is_file():
        return candidate
    for base in FALLBACK_SEARCH_DIRS:
        candidate = (base / include_path).resolve()
        if candidate.is_file():
            return candidate
    return None


def amalgamate() -> str:
    visited = set()
    body_lines = []

    def process(path: Path):
        path = path.resolve()
        if path in visited:
            return
        visited.add(path)
        text = path.read_text(encoding="utf-8")
        rel = path.relative_to(PROJECT_ROOT)
        body_lines.append(f"\n// ---- {rel.as_posix()} ----\n")
        for line, is_code in scan_lines(text):
            if is_code:
                m = LOCAL_INCLUDE_RE.match(line)
                if m:
                    resolved = resolve_local_include(path.parent, m.group(1))
                    if resolved is not None:
                        process(resolved)
                        continue
                    # Unresolvable quoted include; should not happen in
                    # practice, kept as-is as a fallback.
                    body_lines.append(line)
                    continue
                if PRAGMA_ONCE_RE.match(line):
                    # Each file is only expanded once (see the `visited`
                    # guard above) and the output already carries a single
                    # top-level #pragma once, so per-file ones are dropped.
                    continue
            body_lines.append(line)

    for entry in ENTRY_HEADERS:
        process(entry)

    parts = [HEADER_BANNER, "#pragma once\n"]
    parts.extend(body_lines)
    return "\n".join(parts) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o", "--output",
        default=DEFAULT_OUTPUT,
        type=Path,
        help=f"Output path for the generated single header "
             f"(default: {DEFAULT_OUTPUT.relative_to(PROJECT_ROOT)})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only verify the existing file matches a fresh regeneration; "
             "don't write. Intended for CI / pre-commit checks.",
    )
    args = parser.parse_args()

    content = amalgamate()

    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else None
        if existing == content:
            print(f"OK: {args.output} is up to date.")
            return
        print(
            f"STALE: {args.output} is out of date. Re-run "
            f"`python3 scripts/amalgamate.py` and commit the result.",
            file=sys.stderr,
        )
        sys.exit(1)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Generated {args.output} ({len(content.splitlines())} lines)")


if __name__ == "__main__":
    main()
